server:
    port: 8080
    compression:
        enabled: true
spring:
    application:
        name: product-management
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
    main:
        allow-circular-references: true
    datasource:
        url: jdbc:h2:mem:product-management
        driver-class-name: org.h2.Driver
        username: sa
        password:
        hikari:
            auto-commit: false
            connection-timeout: 20000
            minimum-idle: 5
            maximum-pool-size: 10
            idle-timeout: 300000
            max-lifetime: 1200000
            pool-name: ProductManagerPool
    jpa:
        .properties:
            hibernate:
                enable_lazy_load_no_trans: true
                ddl-auto: create-drop
                format_sql: true
        show-sql: true
        open-in-view: off
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console
    security:
        user:
            name: admin
            password: password
springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    show-actuator: true
    packages-to-scan: io.ennov.productmanagement.controller
management:
    endpoints:
        web:
            exposure:
                include: '*'
            base-path: /actuator
